- hosts: appserver
  become: true
  gather_facts: true

  vars:
    docker_net: monitoring-net
    grafana_name: grafana
    grafana_image: grafana/grafana:latest
    grafana_port_host: 3001
    grafana_admin_user: abim
    grafana_admin_pass: "abim123" # ganti / pakai Ansible Vault ya

  pre_tasks:
    - name: Ensure docker network
      community.docker.docker_network:
        name: "{{ docker_net }}"
        state: present

    - name: Ensure volume for grafana data
      community.docker.docker_volume:
        name: grafana-data
        state: present

  tasks:
    - name: Run Grafana
      community.docker.docker_container:
        name: "{{ grafana_name }}"
        image: "{{ grafana_image }}"
        restart_policy: always
        state: started
        published_ports:
          - "{{ grafana_port_host }}:3000"
        networks:
          - name: "{{ docker_net }}"
        volumes:
          - "grafana-data:/var/lib/grafana"
        env:
          GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
          GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pass }}"

    - name: (Opsional) buka UFW untuk Grafana jika aktif
      ansible.builtin.shell: ufw status
      register: ufw
      changed_when: false
      failed_when: false

    - name: Open port 3001 on UFW
      ansible.builtin.ufw:
        rule: allow
        port: "{{ grafana_port_host }}"
        proto: tcp
      when: "'Status: active' in (ufw.stdout | default(''))"

    - name: Print URL
      ansible.builtin.debug:
        msg: "Grafana → http://{{ ansible_default_ipv4.address }}:{{ grafana_port_host }} ({{ grafana_admin_user }}/{{ grafana_admin_pass }})"
