- hosts: appserver
  become: true
  gather_facts: true

  vars:
    jenkins_home: /opt/jenkins/home
    jenkins_compose_dir: /opt/jenkins
    jenkins_http_port: 8080
    jenkins_agent_port: 50000

  tasks:
    - name: Buat folder Jenkins (home & compose dir)
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ jenkins_home }}"
        - "{{ jenkins_compose_dir }}"

    - name: Tulis docker-compose.yml untuk Jenkins
      copy:
        dest: "{{ jenkins_compose_dir }}/docker-compose.yml"
        content: |
          version: "3.8"
          services:
            jenkins:
              image: jenkins/jenkins:lts-jdk17
              container_name: jenkins
              user: "0:0"
              restart: unless-stopped
              ports:
                - "{{ jenkins_http_port }}:8080"
                - "{{ jenkins_agent_port }}:50000"
              environment:
                - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
                - JENKINS_HOME=/var/jenkins_home
              volumes:
                - "{{ jenkins_home }}:/var/jenkins_home"
                - /var/run/docker.sock:/var/run/docker.sock
                - /usr/bin/docker:/usr/bin/docker

    - name: Jalankan Jenkins (docker compose up -d)
      command: docker compose up -d
      args:
        chdir: "{{ jenkins_compose_dir }}"

    # Buka port kalau UFW aktif (kalau inactive, langkah ini otomatis di-skip)
    - block:
        - name: Cek apakah UFW aktif
          shell: 'ufw status | grep -qi "^Status: active"'
          register: ufw_active
          changed_when: false
          failed_when: false

        - name: Allow port Jenkins HTTP
          command: ufw allow {{ jenkins_http_port }}/tcp
          when: ufw_active.rc == 0

        - name: Allow port Jenkins agent (JNLP)
          command: ufw allow {{ jenkins_agent_port }}/tcp
          when: ufw_active.rc == 0

        - name: Reload UFW
          command: ufw reload
          when: ufw_active.rc == 0
      when: ansible_facts['os_family'] == 'Debian'

    - name: Info cara unlock Jenkins
      debug:
        msg:
          - "Akses Jenkins: http://{{ ansible_default_ipv4.address | default(inventory_hostname) }}:{{ jenkins_http_port }}"
          - "Password awal (host): {{ jenkins_home }}/secrets/initialAdminPassword"
          - "Password awal (container): docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword"
