- hosts: gatewayserver
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is enabled and running
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Setup reverse proxy - Production frontend
      copy:
        dest: /etc/nginx/sites-available/prod-frontend.conf
        content: |
          server {
              listen 80;
              server_name abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Production backend
      copy:
        dest: /etc/nginx/sites-available/prod-backend.conf
        content: |
          server {
              listen 80;
              server_name api.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Pipeline jenkins
      copy:
        dest: /etc/nginx/sites-available/pipeline-jenkins.conf
        content: |
          server {
              listen 80;
              server_name staging.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Staging frontend
      copy:
        dest: /etc/nginx/sites-available/staging-frontend.conf
        content: |
          server {
              listen 80;
              server_name staging.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:3002;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Staging backend
      copy:
        dest: /etc/nginx/sites-available/staging-backend.conf
        content: |
          server {
              listen 80;
              server_name api.staging.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://127.0.0.1:5002;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Registry
      copy:
        dest: /etc/nginx/sites-available/registry.conf
        content: |
          server {
              listen 80;
              server_name registry.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:5001;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Grafana
      copy:
        dest: /etc/nginx/sites-available/grafana.conf
        content: |
          server {
              listen 80;
              server_name monitoring.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:3001;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Prometheus
      copy:
        dest: /etc/nginx/sites-available/prometheus.conf
        content: |
          server {
              listen 80;
              server_name prom.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:9090;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Setup reverse proxy - Node Exporter
      copy:
        dest: /etc/nginx/sites-available/exporter.conf
        content: |
          server {
              listen 80;
              server_name exporter.abimft.studentdumbways.my.id;

              location / {
                  proxy_pass http://103.196.152.65:9100;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable sites
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      loop:
        - prod-frontend.conf
        - prod-backend.conf
        - staging-frontend.conf
        - staging-backend.conf
        - registry.conf
        - grafana.conf
        - prometheus.conf
        - exporter.conf

    - name: Test Nginx config
      command: nginx -t

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
