- hosts: appserver
  become: true
  gather_facts: false

  vars:
    docker_net: monitoring-net
    mon_base: /opt/monitoring
    prom_cfg: "{{ mon_base }}/prometheus/prometheus.yml"
    prom_name: prometheus
    prom_image: prom/prometheus:latest
    prom_port_host: 9090

  pre_tasks:
    - name: Ensure directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ mon_base }}"
        - "{{ mon_base }}/prometheus"

    - name: Write Prometheus config (scrape node-exporter dari 2 server)
      ansible.builtin.copy:
        dest: "{{ prom_cfg }}"
        mode: "0644"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets:
                    - "103.175.220.38:9100"  # gatewayserver
                    - "103.196.152.65:9100"  # appserver

    - name: Ensure docker network
      community.docker.docker_network:
        name: "{{ docker_net }}"
        state: present

    - name: Ensure volume for prometheus data
      community.docker.docker_volume:
        name: prom-data
        state: present

  tasks:
    - name: Run Prometheus
      community.docker.docker_container:
        name: "{{ prom_name }}"
        image: "{{ prom_image }}"
        restart_policy: always
        state: started
        published_ports:
          - "{{ prom_port_host }}:9090"
        networks:
          - name: "{{ docker_net }}"
        volumes:
          - "{{ prom_cfg }}:/etc/prometheus/prometheus.yml:ro"
          - "prom-data:/prometheus"
