- hosts: appserver
  become: true
  gather_facts: false

  vars:
    fe_repo_url: "https://github.com/abimsyaefulloh/fe-dumbmerch.git"
    fe_repo_version: "main"
    fe_repo_dest: "/opt/fe-dumbmerch-staging"

    fe_container_name: "fe-dumbmerch-staging"
    fe_host_port: 3002 # <- sesuai nginx staging frontend
    fe_container_port: 3000 # port di dalam container FE

    # base URL API untuk STAGING (pakai http karena reverse proxy nginx di :80)
    fe_staging_api_base: "http://api.staging.abimft.studentdumbways.my.id/api/v1"

  tasks:
    - name: Ensure workdir exists
      file:
        path: "{{ fe_repo_dest }}"
        state: directory

    - name: Clone FE repo (staging)
      git:
        repo: "{{ fe_repo_url }}"
        dest: "{{ fe_repo_dest }}"
        version: "{{ fe_repo_version }}"
        force: true

    # Patch baseURL ke domain STAGING (best-effort, cari "baseURL" di file .js/.ts)
    - name: Patch FE baseURL to staging
      shell: |
        set -e
        cd "{{ fe_repo_dest }}"
        files=$(grep -RIl --include="*.js" --include="*.jsx" --include="*.ts" --include="*.tsx" -e 'baseURL' . || true)
        if [ -n "$files" ]; then
          for f in $files; do
            sed -ri 's#baseURL:\s*"[^\"]+"#baseURL: "{{ fe_staging_api_base }}"#g' "$f"
          done
        fi
      args:
        executable: /bin/bash

    - name: Create docker-compose.staging.yml for FE
      copy:
        dest: "{{ fe_repo_dest }}/docker-compose.staging.yml"
        content: |
          services:
            fe:
              build: .
              container_name: {{ fe_container_name }}
              ports:
                - "{{ fe_host_port }}:{{ fe_container_port }}"
              restart: always

    - name: Compose up FE staging
      command: docker compose -f docker-compose.staging.yml up -d --build
      args:
        chdir: "{{ fe_repo_dest }}"

    - name: Show FE staging URL
      debug:
        msg: "FE staging via Nginx: http://staging.abimft.studentdumbways.my.id  (proxy ke port {{ fe_host_port }})"
